//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the pose_follower package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __pose_follower__POSEFOLLOWERCONFIG_H__
#define __pose_follower__POSEFOLLOWERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace pose_follower
{
  class PoseFollowerConfigStatics;

  class PoseFollowerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PoseFollowerConfig &config, const PoseFollowerConfig &max, const PoseFollowerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PoseFollowerConfig &config1, const PoseFollowerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PoseFollowerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PoseFollowerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PoseFollowerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PoseFollowerConfig &config) const = 0;
      virtual void getValue(const PoseFollowerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PoseFollowerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PoseFollowerConfig::* field;

      virtual void clamp(PoseFollowerConfig &config, const PoseFollowerConfig &max, const PoseFollowerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PoseFollowerConfig &config1, const PoseFollowerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PoseFollowerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PoseFollowerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PoseFollowerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PoseFollowerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PoseFollowerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PoseFollowerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PoseFollowerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PoseFollowerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PoseFollowerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_vel_lin"==(*_i)->name){max_vel_lin = boost::any_cast<double>(val);}
        if("max_vel_th"==(*_i)->name){max_vel_th = boost::any_cast<double>(val);}
        if("min_vel_lin"==(*_i)->name){min_vel_lin = boost::any_cast<double>(val);}
        if("min_vel_th"==(*_i)->name){min_vel_th = boost::any_cast<double>(val);}
        if("min_in_place_vel_th"==(*_i)->name){min_in_place_vel_th = boost::any_cast<double>(val);}
        if("in_place_trans_vel"==(*_i)->name){in_place_trans_vel = boost::any_cast<double>(val);}
        if("trans_stopped_velocity"==(*_i)->name){trans_stopped_velocity = boost::any_cast<double>(val);}
        if("rot_stopped_velocity"==(*_i)->name){rot_stopped_velocity = boost::any_cast<double>(val);}
        if("tolerance_trans"==(*_i)->name){tolerance_trans = boost::any_cast<double>(val);}
        if("tolerance_rot"==(*_i)->name){tolerance_rot = boost::any_cast<double>(val);}
        if("tolerance_timeout"==(*_i)->name){tolerance_timeout = boost::any_cast<double>(val);}
        if("samples"==(*_i)->name){samples = boost::any_cast<int>(val);}
        if("allow_backwards"==(*_i)->name){allow_backwards = boost::any_cast<bool>(val);}
        if("turn_in_place_first"==(*_i)->name){turn_in_place_first = boost::any_cast<bool>(val);}
        if("max_heading_diff_before_moving"==(*_i)->name){max_heading_diff_before_moving = boost::any_cast<double>(val);}
        if("k_trans"==(*_i)->name){k_trans = boost::any_cast<double>(val);}
        if("k_rot"==(*_i)->name){k_rot = boost::any_cast<double>(val);}
      }
    }

    double max_vel_lin;
double max_vel_th;
double min_vel_lin;
double min_vel_th;
double min_in_place_vel_th;
double in_place_trans_vel;
double trans_stopped_velocity;
double rot_stopped_velocity;
double tolerance_trans;
double tolerance_rot;
double tolerance_timeout;
int samples;
bool allow_backwards;
bool turn_in_place_first;
double max_heading_diff_before_moving;
double k_trans;
double k_rot;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_vel_lin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_vel_th;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_vel_lin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_vel_th;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_in_place_vel_th;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double in_place_trans_vel;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double trans_stopped_velocity;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rot_stopped_velocity;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tolerance_trans;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tolerance_rot;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tolerance_timeout;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int samples;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool allow_backwards;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool turn_in_place_first;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_heading_diff_before_moving;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_trans;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_rot;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PoseFollowerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PoseFollowerConfig &__max__ = __getMax__();
      const PoseFollowerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PoseFollowerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PoseFollowerConfig &__getDefault__();
    static const PoseFollowerConfig &__getMax__();
    static const PoseFollowerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PoseFollowerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PoseFollowerConfig::ParamDescription<std::string>::clamp(PoseFollowerConfig &config, const PoseFollowerConfig &max, const PoseFollowerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PoseFollowerConfigStatics
  {
    friend class PoseFollowerConfig;

    PoseFollowerConfigStatics()
    {
PoseFollowerConfig::GroupDescription<PoseFollowerConfig::DEFAULT, PoseFollowerConfig> Default("Default", "", 0, 0, true, &PoseFollowerConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_vel_lin = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_vel_lin = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_vel_lin = 0.9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_vel_lin", "double", 0, "Maximum linear velocity in m/s", "", &PoseFollowerConfig::max_vel_lin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_vel_lin", "double", 0, "Maximum linear velocity in m/s", "", &PoseFollowerConfig::max_vel_lin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_vel_th = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_vel_th = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_vel_th = 1.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_vel_th", "double", 0, "Maximum angular velocity in rad/s", "", &PoseFollowerConfig::max_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_vel_th", "double", 0, "Maximum angular velocity in rad/s", "", &PoseFollowerConfig::max_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_vel_lin = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_vel_lin = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_vel_lin = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_vel_lin", "double", 0, "Minimum linear velocity for the robot in m/s", "", &PoseFollowerConfig::min_vel_lin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_vel_lin", "double", 0, "Minimum linear velocity for the robot in m/s", "", &PoseFollowerConfig::min_vel_lin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_vel_th = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_vel_th = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_vel_th = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_vel_th", "double", 0, "Minimum angular velocity for the robot in rad/s", "", &PoseFollowerConfig::min_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_vel_th", "double", 0, "Minimum angular velocity for the robot in rad/s", "", &PoseFollowerConfig::min_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_in_place_vel_th = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_in_place_vel_th = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_in_place_vel_th = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_in_place_vel_th", "double", 0, "If we're rotating in place, go at least this fast to avoid getting stuck", "", &PoseFollowerConfig::min_in_place_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("min_in_place_vel_th", "double", 0, "If we're rotating in place, go at least this fast to avoid getting stuck", "", &PoseFollowerConfig::min_in_place_vel_th)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.in_place_trans_vel = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.in_place_trans_vel = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.in_place_trans_vel = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("in_place_trans_vel", "double", 0, "When we're near the end and would be trying to go no faster than this translationally, just rotate in place instead", "", &PoseFollowerConfig::in_place_trans_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("in_place_trans_vel", "double", 0, "When we're near the end and would be trying to go no faster than this translationally, just rotate in place instead", "", &PoseFollowerConfig::in_place_trans_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.trans_stopped_velocity = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.trans_stopped_velocity = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.trans_stopped_velocity = 0.0001;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("trans_stopped_velocity", "double", 0, "The robot is stopped if the velocities are lower than this", "", &PoseFollowerConfig::trans_stopped_velocity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("trans_stopped_velocity", "double", 0, "The robot is stopped if the velocities are lower than this", "", &PoseFollowerConfig::trans_stopped_velocity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rot_stopped_velocity = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rot_stopped_velocity = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rot_stopped_velocity = 0.0001;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("rot_stopped_velocity", "double", 0, "The robot is stopped if the velocities are lower than this", "", &PoseFollowerConfig::rot_stopped_velocity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("rot_stopped_velocity", "double", 0, "The robot is stopped if the velocities are lower than this", "", &PoseFollowerConfig::rot_stopped_velocity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tolerance_trans = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tolerance_trans = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tolerance_trans = 0.02;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_trans", "double", 0, "Translational tolerance for the goal", "", &PoseFollowerConfig::tolerance_trans)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_trans", "double", 0, "Translational tolerance for the goal", "", &PoseFollowerConfig::tolerance_trans)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tolerance_rot = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tolerance_rot = 3.141592653589793;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tolerance_rot = 0.04;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_rot", "double", 0, "Angular tolerance for the goal", "", &PoseFollowerConfig::tolerance_rot)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_rot", "double", 0, "Angular tolerance for the goal", "", &PoseFollowerConfig::tolerance_rot)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tolerance_timeout = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tolerance_timeout = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tolerance_timeout = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_timeout", "double", 0, "We've reached our goal only if we're within range for this long and stopped", "", &PoseFollowerConfig::tolerance_timeout)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("tolerance_timeout", "double", 0, "We've reached our goal only if we're within range for this long and stopped", "", &PoseFollowerConfig::tolerance_timeout)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.samples = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.samples = 20;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.samples = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<int>("samples", "int", 0, "Number of samples (scaling factors of our current desired twist)", "", &PoseFollowerConfig::samples)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<int>("samples", "int", 0, "Number of samples (scaling factors of our current desired twist)", "", &PoseFollowerConfig::samples)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.allow_backwards = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.allow_backwards = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.allow_backwards = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<bool>("allow_backwards", "bool", 0, "Allow backwards movement", "", &PoseFollowerConfig::allow_backwards)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<bool>("allow_backwards", "bool", 0, "Allow backwards movement", "", &PoseFollowerConfig::allow_backwards)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.turn_in_place_first = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.turn_in_place_first = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.turn_in_place_first = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<bool>("turn_in_place_first", "bool", 0, "If true, turn in place to face the new goal instead of arching towards it", "", &PoseFollowerConfig::turn_in_place_first)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<bool>("turn_in_place_first", "bool", 0, "If true, turn in place to face the new goal instead of arching towards it", "", &PoseFollowerConfig::turn_in_place_first)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_heading_diff_before_moving = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_heading_diff_before_moving = 3.141592653589793;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_heading_diff_before_moving = 0.17;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_heading_diff_before_moving", "double", 0, "If turn_in_place_first is true, turn in place if our heading is more than this far from facing the goal location", "", &PoseFollowerConfig::max_heading_diff_before_moving)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("max_heading_diff_before_moving", "double", 0, "If turn_in_place_first is true, turn in place if our heading is more than this far from facing the goal location", "", &PoseFollowerConfig::max_heading_diff_before_moving)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_trans = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_trans = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_trans = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("k_trans", "double", 0, "Gain factor for translation component of output velocities", "", &PoseFollowerConfig::k_trans)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("k_trans", "double", 0, "Gain factor for translation component of output velocities", "", &PoseFollowerConfig::k_trans)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_rot = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_rot = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_rot = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("k_rot", "double", 0, "Gain factor for rotation component of output velocities", "", &PoseFollowerConfig::k_rot)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PoseFollowerConfig::AbstractParamDescriptionConstPtr(new PoseFollowerConfig::ParamDescription<double>("k_rot", "double", 0, "Gain factor for rotation component of output velocities", "", &PoseFollowerConfig::k_rot)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PoseFollowerConfig::AbstractGroupDescriptionConstPtr(new PoseFollowerConfig::GroupDescription<PoseFollowerConfig::DEFAULT, PoseFollowerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PoseFollowerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PoseFollowerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PoseFollowerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PoseFollowerConfig __max__;
    PoseFollowerConfig __min__;
    PoseFollowerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PoseFollowerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PoseFollowerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PoseFollowerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PoseFollowerConfig &PoseFollowerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PoseFollowerConfig &PoseFollowerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PoseFollowerConfig &PoseFollowerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PoseFollowerConfig::AbstractParamDescriptionConstPtr> &PoseFollowerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PoseFollowerConfig::AbstractGroupDescriptionConstPtr> &PoseFollowerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PoseFollowerConfigStatics *PoseFollowerConfig::__get_statics__()
  {
    const static PoseFollowerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PoseFollowerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __POSEFOLLOWERRECONFIGURATOR_H__
